// One-shot: self-host the four site faces. Fetches the provider CSS, downloads
// every woff2, and writes src/styles/fonts.css with url()s rewritten to /fonts/*.
// The brief self-hosts because Fontshare's CDN is not battle-tested on school wifi.
import { writeFile, mkdir, readdir, unlink } from 'node:fs/promises';

const FONTS_DIR = new URL('../public/fonts/', import.meta.url);
const CSS_OUT = new URL('../src/styles/fonts.css', import.meta.url);
await mkdir(FONTS_DIR, { recursive: true });

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const SOURCES = [
  { name: 'Fontshare', url: 'https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@300,400,500&f[]=satoshi@400,500,700&f[]=stardom@400&display=swap' },
  { name: 'Google', url: 'https://fonts.googleapis.com/css2?family=Shantell+Sans:wght@400;500&display=swap' },
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function get(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r;
}

// wipe stale files so re-runs are clean
for (const f of await readdir(FONTS_DIR)) await unlink(new URL(f, FONTS_DIR));

let out = '/* Generated by scripts/fetch-fonts.mjs — self-hosted @font-face. Do not edit by hand. */\n';
let count = 0;

for (const src of SOURCES) {
  const css = await (await get(src.url)).text();
  // Split into @font-face blocks so we can name each file by family + weight (+ subset).
  const blocks = css.match(/@font-face\s*{[^}]*}/g) || [];
  const perFamilyWeight = {};
  for (const block of blocks) {
    const family = /font-family:\s*['"]?([^;'"]+)['"]?/.exec(block)?.[1]?.trim();
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    // first woff2 url in the block; may be protocol-relative (//cdn...) or https
    const raw = /url\((['"]?)(\/\/[^)'"]+\.woff2|https:[^)'"]+\.woff2)\1\)/.exec(block)?.[2];
    if (!family || !raw) continue;
    const url = raw.startsWith('//') ? 'https:' + raw : raw;
    const key = `${slug(family)}-${weight}`;
    const idx = (perFamilyWeight[key] = (perFamilyWeight[key] ?? -1) + 1);
    const fname = idx === 0 ? `${key}.woff2` : `${key}-${idx}.woff2`;
    const buf = Buffer.from(await (await get(url)).arrayBuffer());
    await writeFile(new URL(fname, FONTS_DIR), buf);
    count++;
    out +=
      `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};` +
      `font-display:swap;src:url('/fonts/${fname}') format('woff2');` +
      (range ? `unicode-range:${range};` : '') +
      `}\n`;
    console.log(`saved ${fname} (${(buf.length / 1024).toFixed(0)}KB)`);
  }
}

await writeFile(CSS_OUT, out);
console.log(`done: ${count} files -> src/styles/fonts.css`);
